### ISSUE TITLE
Computing data members ignores initialization through functions

### ISSUE THREAD

**Issue by atzannes** [ufora/ufora#103]
In the code below we return the empty set (we don't find any of the data members). Instead we should either throw or descend into member functions.
```python
    def test_computeDataMembers_5(self):
        class C5:
            def __init__(self, arg):
                self.initialize(arg)
            def initialize(self, arg):
                (self.x, self.y), self.z = arg

        dataMembers = PyAstUtil.computeDataMembers(C5)

        self.assertEqual(
            dataMembers,
            set(['x', 'y', 'z'])
            )
```

**Comment by tdp2110** [comment]
maybe we should just give a more descriptive name to `PyAstUtil.computeDataMembers`: it's only computing "simple" ones, given by assignment in `__init__`. This won't pass the rest of our codegen, however, since we don't allow such assignments in `initialize`
