### ISSUE TITLE
list getitem doesn't throw with step 0

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#109]

**Comment by tdp2110** [comment]
for example, in python, `[][::0]` raises `ValueError("slice step cannot be zero")`

fora is perfectly happy with this

**Comment by braxtonmckee** [comment]
yeah, that's no good...

On Tue, Nov 10, 2015 at 4:53 PM, Thomas Peters <notifications@github.com>
wrote:

> for example, in python, [][::0] raises ValueError("slice step cannot be
> zero")
>
> fora is perfectly happy with this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/109#issuecomment-155578555>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com
