### ISSUE TITLE
Out of core support on a single node (and integration with other projects) 

### ISSUE THREAD

**Issue by datnamer** [ufora/ufora#118]
My use case involves analyst's working on single machine datasets that don't fit in ram. Is there currently a way to run code on a single node on disk sqlite and or hdf5 file?

Right now things like Dask and Blaze http://blaze.pydata.org/ are helpful with data munging/aggregation/ large dataframes , but don't provide a way to do the statistical modeling. 

Even better would be if ufora can find a way for there to be a clean interface with the aformentioned projects (which are gaining steam). 

Then there is bokeh for visualization: https://github.com/bokeh/bokeh

**Comment by braxtonmckee** [comment]
Hi Datnamer. Sorry for the delay - I just got finshed at MLconf.

Currently, it's pretty easy to run on one node, but Ufora really focuses on problems where all data can fit in RAM (in aggregate over the cluster). We can certainly handle the case where the data is on disk, but we are not optimized for it (although that will eventually change).

In terms of import/export, we've got S3 implemented, (HDFS also, but not yet exposed in python, that should be coming very soon). Local file system would also be trivial, so we can prioritize that if we get some more requests.

If the data fits into memory across a cluster (totally feasible for TB, obviously not as practical for PB) then that's the best for our current infrastructure. If you're willing to run in the cloud, that's pretty easy to do.

On Dask/Blaze stuff, we are working hard to be able to replicate both pandas and scikit. We certainly could also mimic the interfaces of blaze and dask, or at the very least be able to easiily read data from them in/out of ufora. Similarly with bokeh (actually, that should be pretty straightforward).

Let me know if I can add any detail on these points.

Thanks for asking!

**Comment by datnamer** [comment]
Thanks for your response.

It seems like blaze/dask integration would be really cool...especially if those datastructures catch more appeal.

Definitely the single node out of core use case appeals most to myself and the work I do. This is also  currently something only SAS and maybe revaluation analytics handles well.  The former is retaining popularity for just that reason and thus I think single node analytics would be a great niche for ufora...coupled with the work being done on dask and bokeh. 

The other less urgent use case is agent based models, with classes that interact using distributed computation. These classes maintain state so I don't know if they would be amenable to Ufora's optimizations.
