### ISSUE TITLE
implement `assert`

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#124]
I love using asserts in code, and I'm sorely missing them. ;_;

**Comment by braxtonmckee** [comment]
+1 this should be cheap and v. useful. Mark for 0.3

On Mon, Nov 16, 2015 at 12:57 PM, Thomas Peters <notifications@github.com>
wrote:

> I love using asserts in code, and I'm sorely missing them. ;_;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/124>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by braxtonmckee** [comment]
Or 0.2 if you feel it's important for DF work.

On Mon, Nov 16, 2015 at 1:24 PM, Braxton McKee <braxton.mckee@gmail.com>
wrote:

> +1 this should be cheap and v. useful. Mark for 0.3
>
> On Mon, Nov 16, 2015 at 12:57 PM, Thomas Peters <notifications@github.com>
> wrote:
>
>> I love using asserts in code, and I'm sorely missing them. ;_;
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ufora/ufora/issues/124>.
>>
>
>
>
> --
>
> -------------------------------------------------------------------------------------------
> Braxton McKee                             CEO / Ufora
> www.twitter.com/braxtonmckee       www.ufora.com
>
>


-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by tdp2110** [comment]
it can wait, but I do miss it

On Mon, Nov 16, 2015 at 1:24 PM, Braxton McKee <notifications@github.com>
wrote:

> Or 0.2 if you feel it's important for DF work.
>
> On Mon, Nov 16, 2015 at 1:24 PM, Braxton McKee <braxton.mckee@gmail.com>
> wrote:
>
>
> > +1 this should be cheap and v. useful. Mark for 0.3
> >
> > On Mon, Nov 16, 2015 at 12:57 PM, Thomas Peters <
> notifications@github.com>
> > wrote:
> >
> >> I love using asserts in code, and I'm sorely missing them. ;_;
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/ufora/ufora/issues/124>.
> >>
> >
> >
> >
> > --
> >
> >
> -------------------------------------------------------------------------------------------
> > Braxton McKee CEO / Ufora
> > www.twitter.com/braxtonmckee www.ufora.com
> >
> >
>
>
> --
>
> -------------------------------------------------------------------------------------------
> Braxton McKee CEO / Ufora
> www.twitter.com/braxtonmckee www.ufora.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/124#issuecomment-157127163>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com
