### ISSUE TITLE
bad error message when accessing self in `__init__` (without a setitem/getitem)

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#126]
for example:

    class C:
        def __init__(self):
            str(self)
    def f():
        C()
    
you'll get an error:

```
PythonToForaConversionError: An internal error occurred: we didn't provide a definition for the following variables: ['self']. Most likely, there is a mismatch between our analysis of the python code and the generated FORA code underneath. Please file a bug report.
```

this is a little tricky, if we're going to allow this since we don't actually have a class instance until we actually call the fora function `createInstance` in generated code. At the very least we could disallow this and give a better error message which documents the restrictions.

**Comment by braxtonmckee** [comment]
I already added something so that you can't "return" in __init__. We should
do the same thing here.

On Mon, Nov 16, 2015 at 2:19 PM, Thomas Peters <notifications@github.com>
wrote:

> for example:
>
> class C:
>     def __init__(self):
>         str(self)
> def f():
>     C()
>
> you'll get an error:
>
> PythonToForaConversionError: An internal error occurred: we didn't provide a definition for the following variables: ['self']. Most likely, there is a mismatch between our analysis of the python code and the generated FORA code underneath. Please file a bug report.
>
> this is a little tricky, if we're going to allow this since we don't
> actually have a class instance until we actually call the fora function
> createInstance in generated code. At the very least we could disallow
> this and give a better error message which documents the restrictions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/126>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by tdp2110** [comment]
I saw your commit which disallows `return` in `__init__`. @atzannes had a
front-end (python) approach for something similar, which was used in 6d51de9

On Mon, Nov 16, 2015 at 2:32 PM, Braxton McKee <notifications@github.com>
wrote:

> I already added something so that you can't "return" in __init__. We should
> do the same thing here.
>
> On Mon, Nov 16, 2015 at 2:19 PM, Thomas Peters <notifications@github.com>
> wrote:
>
> > for example:
> >
> > class C:
> > def __init__(self):
> > str(self)
> > def f():
> > C()
> >
> > you'll get an error:
> >
> > PythonToForaConversionError: An internal error occurred: we didn't
> provide a definition for the following variables: ['self']. Most likely,
> there is a mismatch between our analysis of the python code and the
> generated FORA code underneath. Please file a bug report.
> >
> > this is a little tricky, if we're going to allow this since we don't
> > actually have a class instance until we actually call the fora function
> > createInstance in generated code. At the very least we could disallow
> > this and give a better error message which documents the restrictions.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ufora/ufora/issues/126>.
> >
>
>
>
> --
>
> -------------------------------------------------------------------------------------------
> Braxton McKee CEO / Ufora
> www.twitter.com/braxtonmckee www.ufora.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/126#issuecomment-157145163>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com
