### ISSUE TITLE
pyfora range function should not accept non-integer arguments

### ISSUE THREAD

**Issue by braxtonmckee** [ufora/ufora#131]
but it _should_ try to cast them to integer. Right now it just does the wrong thing.

**Comment by tdp2110** [comment]
python `range` requires `int` arguments

**Comment by tdp2110** [comment]
@braxtonmckee what's the "wrong thing"?

it shouldn't accept non-integer arguments, but should cast them to int?

**Comment by braxtonmckee** [comment]
It should do whatever regular python does, which is to throw an exception.

On Mon, Jan 25, 2016 at 9:52 AM, Thomas Peters <notifications@github.com>
wrote:

> @braxtonmckee <https://github.com/braxtonmckee> what's the "wrong thing"?
>
> it shouldn't accept non-integer arguments, but should cast them to int?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/131#issuecomment-174530080>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com
