### ISSUE TITLE
PyAstUtil cleanup

### ISSUE THREAD

**Issue by atzannes** [ufora/ufora#132]
There are functions (see below) that do very similar things, in very similar ways. We can probably merge some and remove some from the public API.

Here's a possibly incomplete list:
```python
def getSourceText(pyObject):

def getSourceFilenameAndText(pyObject):

def getSourceFileText(pyObject):

def pyAstFromText(text):

def pyAstFor(pyObject):

def getSourceFileAst(pyObject):

def getAstFromFilePath(filename):
```

**Comment by tdp2110** [comment]
we can also pull all of that ast stuff into its own subdirectory

**Comment by atzannes** [comment]
so, I'm making a pyAst subdirectory and pulling in PyAstUtil, PyAstFreeVariableAnalyses, and NodeVisitorBases. My question is where should the corresponding test files live. Right now they are in `pyfora.test`. Should I move them to `pyfora.pyAst`, to `pyfora.pyAst.test`, or leave them where they are?

**Comment by tdp2110** [comment]
I've seen both patterns, but I'd be fine with them all living just in
pyfora.test for now

On Mon, Dec 14, 2015 at 2:05 PM, Alexandros Tzannes <
notifications@github.com> wrote:

> so, I'm making a pyAst subdirectory and pulling in PyAstUtil,
> PyAstFreeVariableAnalyses, and NodeVisitorBases. My question is where
> should the corresponding test files live. Right now they are in
> pyfora.test. Should I move them to pyfora.pyAst, to pyfora.pyAst.test, or
> leave them where they are?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/132#issuecomment-164527956>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com

**Comment by atzannes** [comment]
Ok, the looper seems happy. @tdp2110  could you review the two commits referencing #132 listed above?

**Comment by tdp2110** [comment]
looks good to me too. go for it!

On Mon, Dec 14, 2015 at 3:48 PM, Alexandros Tzannes <
notifications@github.com> wrote:

> Ok, the looper seems happy. @tdp2110 <https://github.com/tdp2110> could
> you review the two commits referencing #132
> <https://github.com/ufora/ufora/issues/132> listed above?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/132#issuecomment-164554961>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com

**Comment by atzannes** [comment]
Done
