### ISSUE TITLE
no support for object inheritance

### ISSUE THREAD

**Issue by braxtonmckee** [ufora/ufora#133]
At a minimum, we should allow inheriting from `object`. But we should really be able to support the full python inheritance model, as long as we have simple constructors.

**Comment by ronenh** [comment]
dd2c6de adds "Initial support for class inheritance"

**Comment by ronenh** [comment]
`super(...)` is still not supported, but apart from that inheritance is a-go.

**Comment by tdp2110** [comment]
:+1::+1::+1:
