### ISSUE TITLE
python problems on osx

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#136]
I can successfully build (in docker) ufora/build on my mac, but I can't import pyfora (yes I pip installed it):

```
root@67f621a08d16:/volumes/src# python
Python 2.7.9 (default, Oct 29 2015, 00:36:10) 
[GCC 4.2.1 Compatible Ubuntu Clang 3.5.0 (tags/RELEASE_350/final)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfora
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/volumes/src/packages/python/pyfora/__init__.py", line 34, in <module>
    from pyfora.Connection import connect
  File "/volumes/src/packages/python/pyfora/Connection.py", line 22, in <module>
    import pyfora.Executor as Executor
  File "/volumes/src/packages/python/pyfora/Executor.py", line 29, in <module>
    import pyfora.DefaultPureImplementationMappings as DefaultPureImplementationMappings
  File "/volumes/src/packages/python/pyfora/DefaultPureImplementationMappings.py", line 17, in <module>
    import pyfora.typeConverters.Numpy as Numpy
  File "/volumes/src/packages/python/pyfora/typeConverters/Numpy.py", line 16, in <module>
    import numpy as np
  File "/volumes/src/packages/python/pyfora/typeConverters/numpy.py", line 280, in <module>
    mappings_ = [(np.zeros, NpZeros), (np.array, NpArray), 
AttributeError: 'module' object has no attribute 'zeros'
```

The problem here is that in Numpy.py, we have `import numpy a np`, _which actually refers to Numpy.py, *not* the usual numpy module_. I think @braxtonmckee had a similar problem on windows?

**Comment by braxtonmckee** [comment]
Yes - it was case sensitivity of windows. The Numpy module shadows the real
module. Just renaming it to PureNumpy would probably fix it

On Sunday, November 22, 2015, Thomas Peters <notifications@github.com>
wrote:

> I can successfully build (in docker) ufora/build on my mac, but I can't
> import pyfora (yes I pip installed it):
>
> root@67f621a08d16:/volumes/src# python
> Python 2.7.9 (default, Oct 29 2015, 00:36:10)
> [GCC 4.2.1 Compatible Ubuntu Clang 3.5.0 (tags/RELEASE_350/final)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyfora
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/volumes/src/packages/python/pyfora/__init__.py", line 34, in <module>
>     from pyfora.Connection import connect
>   File "/volumes/src/packages/python/pyfora/Connection.py", line 22, in <module>
>     import pyfora.Executor as Executor
>   File "/volumes/src/packages/python/pyfora/Executor.py", line 29, in <module>
>     import pyfora.DefaultPureImplementationMappings as DefaultPureImplementationMappings
>   File "/volumes/src/packages/python/pyfora/DefaultPureImplementationMappings.py", line 17, in <module>
>     import pyfora.typeConverters.Numpy as Numpy
>   File "/volumes/src/packages/python/pyfora/typeConverters/Numpy.py", line 16, in <module>
>     import numpy as np
>   File "/volumes/src/packages/python/pyfora/typeConverters/numpy.py", line 280, in <module>
>     mappings_ = [(np.zeros, NpZeros), (np.array, NpArray),
> AttributeError: 'module' object has no attribute 'zeros'
>
> The problem here is that in Numpy.py, we have import numpy a np, *which
> actually refers to Numpy.py, not the usual numpy module*. I think
> @braxtonmckee <https://github.com/braxtonmckee> had a similar problem on
> windows?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/136>.
>


-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com
