### ISSUE TITLE
ufora-worker launched with pyfora_aws only uses 8GB of memory

### ISSUE THREAD

**Issue by ronenh** [ufora/ufora#140]
On a c3.8xlarge machine, with 64GB of ram, we are only using 8!

**Comment by braxtonmckee** [comment]
which begs the question, what are we doing when we are launched on a
machine that has less than 8!

On Mon, Nov 23, 2015 at 2:27 PM, Ronen Hilewicz <notifications@github.com>
wrote:

> On a c3.8xlarge machine, with 64GB of ram, we are only using 8!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/140>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by ronenh** [comment]
That’s exactly what seems to be the case in the test machines.
Those c3.xlarge machines have 7.5GB of RAM and we were setting the memory limit to 10GB (I think it was 8GB for the VDM and 2 for the rest).
Now that Tom lowered the default limit to 75% of physical memory, tests are failing because they’re hitting that limit.

— 
Ronen Hilewicz  | VP of Engineering |  UFORA
115 West 27th Street 7th Floor, New York, NY 10001
646-580-7545  |  ronen@ufora.com
www.ufora.com

On November 23, 2015 at 5:17:45 PM, Braxton McKee (notifications@github.com) wrote:

which begs the question, what are we doing when we are launched on a
machine that has less than 8!

On Mon, Nov 23, 2015 at 2:27 PM, Ronen Hilewicz <notifications@github.com>
wrote:

> On a c3.8xlarge machine, with 64GB of ram, we are only using 8!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/140>.
>



--
-------------------------------------------------------------------------------------------
Braxton McKee CEO / Ufora
www.twitter.com/braxtonmckee www.ufora.com
