### ISSUE TITLE
Effect / Proof Carrying Code | Term Rewriting and Reduction

### ISSUE THREAD

**Issue by sirinath** [ufora/ufora#149]
Since in essence any interaction with the outside world is through IO it will be good to have effect carrying code at the VM level for better optimisation. Effects can be:

 - Memory (allocations, fences)
 - Computation
 - IO

You can use term rewriting and staging to fully optimise the most minimum set of resource usages formally.

**Comment by braxtonmckee** [comment]
In general, we've made the decision to separate IO and side-effects from
pure computation. "Computation" effects transitions between datastructures
in memory in a pure way which the Ufora VM can then optimize.  Computations
don't have any notion of timing, race conditions, etc, so they don't need
to worry about any of this. A separate set of pathways can be used to
import/export these datastructures to external systems, where all the usual
complications apply.

A good example would be our interaction with S3. You can read keys in S3 as
a string, perform fault-tolerant computation on them using Pyfora, and then
write resulting strings back to S3. The writes are triggered by the user's
python program, but outside of the pyfora "with" block. This has the nice
effect of completely separating the place where restricted semantics apply
(e.g. inside of the with block), but where we can get benefits from such
restrictions (e.g. fault tolerance, automatic parallelism, etc.), from the
place where writing to an outside system happens and we lose the ability to
accurately reason about the state of the system during failure.

Incidentally, as this is not an "issue", as much as it is a discussion of
how Ufora works and various directions it might take, I'd suggest we move
this conversation to the ufora-dev mailing list.

On Wed, Nov 25, 2015 at 12:17 AM, Suminda Dharmasena <
notifications@github.com> wrote:

> Since in essence any interaction with the outside world is through IO it
> will be good to have effect carrying code at the VM level for better
> optimisation. Effects can be:
>
>    - Memory (allocations, fences)
>    - Computation
>    - IO
>
> You can use term rewriting and staging to fully optimise the most minimum
> set of resource usages formally.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/149>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com
