### ISSUE TITLE
Web Visual Programming | Spreadsheet Like Functionality

### ISSUE THREAD

**Issue by sirinath** [ufora/ufora#152]
Is it possible to add visual programming where you can develop likes of:

 - Spreadsheet
   - http://www.ankhor.com/
   - https://www.dadisp.com/
   - http://matrex.sourceforge.net/
   - https://www.quantrix.com/
 - Visual Programming
   - http://unisonweb.org/
   - http://witheve.com/

**Comment by braxtonmckee** [comment]
In general, you could use Ufora as the backend to support these kinds of
workflows, but it would be outside the scope of Ufora itself. We want to
ensure users can use Ufora anywhere they can use Python, not dictate a
particular font-end workflow.

On Wed, Nov 25, 2015 at 10:44 AM, Suminda Dharmasena <
notifications@github.com> wrote:

> Is it possible to add visual programming where you can develop likes of:
>
>    - Spreadsheet
>       - http://www.ankhor.com/
>       - https://www.dadisp.com/
>       - http://matrex.sourceforge.net/
>       - https://www.quantrix.com/
>    - Visual Programming
>       - http://unisonweb.org/
>       - http://witheve.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/152>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com
