### ISSUE TITLE
GBM in pyfora

### ISSUE THREAD

**Issue by ronenh** [ufora/ufora#155]

**Comment by tdp2110** [comment]
I'll have to think about this, but the histogram decision tree builder in fora uses `MutableVectors`

**Comment by braxtonmckee** [comment]
We could create a "MutableNumpyArray" kind of model for this if we wanted.

On Wed, Dec 9, 2015 at 4:23 PM, Thomas Peters <notifications@github.com>
wrote:

> I'll have to think about this, but the histogram decision tree builder in
> fora uses MutableVectors
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/155#issuecomment-163395684>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by tdp2110** [comment]
and how should that be triggered by a user (or the runtime)? Normal numpy
people think about such things

On Wed, Dec 9, 2015 at 4:24 PM, Braxton McKee <notifications@github.com>
wrote:

> We could create a "MutableNumpyArray" kind of model for this if we wanted.
>
> On Wed, Dec 9, 2015 at 4:23 PM, Thomas Peters <notifications@github.com>
> wrote:
>
> > I'll have to think about this, but the histogram decision tree builder in
> > fora uses MutableVectors
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ufora/ufora/issues/155#issuecomment-163395684>.
> >
>
>
>
> --
>
> -------------------------------------------------------------------------------------------
> Braxton McKee CEO / Ufora
> www.twitter.com/braxtonmckee www.ufora.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/155#issuecomment-163395995>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com

**Comment by braxtonmckee** [comment]
we could make a special "pyfora.mutable" object that makes a mutable copy
of the array. It would be a no-op in regular python.

On Wed, Dec 9, 2015 at 4:27 PM, Thomas Peters <notifications@github.com>
wrote:

> and how should that be triggered by a user (or the runtime)? Normal numpy
> people think about such things
>
> On Wed, Dec 9, 2015 at 4:24 PM, Braxton McKee <notifications@github.com>
> wrote:
>
> > We could create a "MutableNumpyArray" kind of model for this if we
> wanted.
> >
> > On Wed, Dec 9, 2015 at 4:23 PM, Thomas Peters <notifications@github.com>
> > wrote:
> >
> > > I'll have to think about this, but the histogram decision tree builder
> in
> > > fora uses MutableVectors
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ufora/ufora/issues/155#issuecomment-163395684>.
> > >
> >
> >
> >
> > --
> >
> >
> -------------------------------------------------------------------------------------------
> > Braxton McKee CEO / Ufora
> > www.twitter.com/braxtonmckee www.ufora.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ufora/ufora/issues/155#issuecomment-163395995>.
> >
>
>
>
> --
> *Thomas Peters* | Software Engineer | *U**FORA *
> 115 West 27th Street 7th Floor, New York, NY 10001
> Office: 646-918-6435 | Mobile: 732-610-8565
> tpeters@ufora.com | www.ufora.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/155#issuecomment-163396573>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by tdp2110** [comment]
I finished the regression tree part of this. working on boosting now

**Comment by tdp2110** [comment]
There are still things we should do here, like multiclass classification and supporting other loss functions, but we have the basics so I'm closing this.
