### ISSUE TITLE
consider relaxing python walker, moving errors to runtime

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#193]
for example, if we have a class

    class C:
        def foo(self): ...
        def bar(self):
            print "bla" # a non-supported pyfora operation

It would be convenient if we could still convert instances of `C`. As long as they don't touch `bar`, we should be able to handle it. If they do touch `bar`, we could raise a runtime exception.

**Comment by ronenh** [comment]
This is closely related to #78.

**Comment by tdp2110** [comment]
#209 duplicated this

**Comment by tdp2110** [comment]
@braxtonmckee did this in d1e3cbf
