### ISSUE TITLE
integrate with iPython notebook.

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#218]
Jupyter too?

**Comment by braxtonmckee** [comment]
yes

On Mon, Feb 22, 2016 at 1:18 PM, Thomas Peters <notifications@github.com>
wrote:

> Jupyter too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/218>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by tdp2110** [comment]
apparently jupyter is just the next generation of ipython notebook
