### ISSUE TITLE
pyfora.connect doesn't propagate failure to connect properly

### ISSUE THREAD

**Issue by braxtonmckee** [ufora/ufora#263]
if we're connecting to an invalid host/port, we just hang.

```
import pyfora
pyfora.connect("localhost:12312")
```

it also appears that the timeout doesn't do anything.

**Comment by UforaInc** [comment]
I have a fix at the top of origin/ronen-ipython. You’ll probably want to squash it into your commit on brax-ipython.


On May 1, 2016 at 10:09:45 PM, Braxton McKee (notifications@github.com) wrote:

if we're connecting to an invalid host/port, we just hang.

import pyfora
pyfora.connect("localhost:12312")

it also appears that the timeout doesn't do anything.
