### ISSUE TITLE
Error following Running pyfora on AWS documentation 

### ISSUE THREAD

**Issue by DrewWham** [ufora/ufora#273]
Hi, I'm attempting to follow your example AWS documentation but something is going wrong after setting up the SSH tunneling. I can get the manager set up and can see it on ec2 console, I can then run your 'test_pyfora.py' script and get the correct result. it seems like 'pyfora.connect('http://localhost:30000')' is working inside of python but outside of python I'm having trouble.

this doesn't work:
$ pyfora_aws add -n 2    
No manager instances are running. Can't add workers.

and this also doesnt work the way I anticipated
$ pyfora_aws list
0 instances

I get the above result after successfully launching the manager with 
$pyfora_aws start --ssh-keyname name_of_your_SSH_keypair

and running this in a separate terminal 
$ ssh -i ssh_key_file -L 30000:localhost:30000 ubuntu@<manager_ip_address>

with <values> correctly changed

am I missing a step?

**Comment by braxtonmckee** [comment]
Did you pick a particular ec2 region? If you override the region, you have
to specify it in all subsequent commants.  What was the exact command you
used to boot the manager?

On Wed, Jul 6, 2016 at 2:23 PM, DrewWham <notifications@github.com> wrote:

> Hi, I'm attempting to follow your example AWS documentation but something
> is going wrong after setting up the SSH tunneling. I can get the manager
> set up and can see it on ec2 console, I can then run your 'test_pyfora.py'
> script and get the correct result. it seems like
> 'pyfora.connect('http://localhost:30000')' is working inside of python
> but outside of python I'm having trouble.
>
> this doesn't work:
> $ pyfora_aws add -n 2
>
> No manager instances are running. Can't add workers.
>
> and this also doesnt work the way I anticipated
> $ pyfora_aws list
> 0 instances
>
> I get the above result after successfully launching the manager with
> $pyfora_aws start --ssh-keyname
>
> and running this is a separate terminal
> $ ssh -i -L 30000:localhost:30000 ubuntu@
>
> with correctly changed
>
> am I missing a step?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufora/ufora/issues/273>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHzjhKN4GpNTZRHbdiKSSbORO-AJ9B1wks5qS_KXgaJpZM4JGXSE>
> .
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by DrewWham** [comment]
Thanks for the quick reply!

I did include --ec2-region us-east-1 but I included that in all cases. 

I used:

$pyfora_aws start --ec2-region us-east-1 --ssh-keyname mykeyname

**Comment by braxtonmckee** [comment]
Sure thing. Next most likely culprit: can you verify that boto credentials
are correctly exported when you're trying to run "pyfora_aws list". They
should be if you ran this in the same shell as the "pyfora_aws start"
command. If boto is connecting to a different account, that will mess
things up.

Also, can you see if the manager node is tagged in the AWS console? It
should be tagged with "pyfora_cluster" set to the cluster name you chose,
or "pyfora" if you didn't pick one. If, for some reason, that didn't work,
it won't see the manager.

On Wed, Jul 6, 2016 at 3:27 PM, DrewWham <notifications@github.com> wrote:

> Thanks for the quick reply!
>
> I did include --ec2-region us-east-1 but I included that in all cases.
>
> I used:
>
> $pyfora_aws start --ec2-region us-east-1 --ssh-keyname mykeyname
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufora/ufora/issues/273#issuecomment-230880609>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHzjhIc2U4DluUAnWV2DQn3ye6WgP2pPks5qTAG_gaJpZM4JGXSE>
> .
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by DrewWham** [comment]
I can see that the managers name is "pyfora manager" and under tags it says "pyfora_cluster" and the value is "pyfora"

As far as the boto credentials, if I enter 
$printenv

I can still see the correct AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID, I assume that would still be passed to boto?

**Comment by braxtonmckee** [comment]
OK, then that all sounds correct.
At this point, to debug what's going on we're going to have to crack open
pyfora_aws itself - I'm not sure why you're not seeing the machines.

Probably the easiest way to do this is to make the pyfora python module
itself writeable and then put print statements into diagnose what's going
on.

if you go to a blank python and write

import pyfora

print pyfora.__file__


you should see the path to where it's installed.  If its installed as root
(probable) you'll either have to edit in sudo or modify the directory so
you can write to it.

At that point, what I'm interested in is what's going on in Launcher.py
(around line 426). Does it see the instances? Simplest thing to do is just
print them out and re-run pyfora_aws.

On Wed, Jul 6, 2016 at 3:52 PM, DrewWham <notifications@github.com> wrote:

> I can see that the managers name is "pyfora manager" and under tags it
> says "pyfora_cluster" and the value is "pyfora"
>
> As far as the boto credentials, if I enter
> $printenv
>
> I can still see the correct AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID, I
> assume that would still be passed to boto?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ufora/ufora/issues/273#issuecomment-230886841>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHzjhDt-rBjGp_mr0Cw2pgzXZcgvYH86ks5qTAeHgaJpZM4JGXSE>
> .
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by ronenh** [comment]
Fixed in version 0.5.7.
