### ISSUE TITLE
Putting a return statement in a Pyfora __init__ causes constructor to not return an instance

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#30]
<a href="https://github.com/braxtonmckee"><img src="https://avatars.githubusercontent.com/u/8184708?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braxtonmckee](https://github.com/braxtonmckee)**
_Monday Oct 19, 2015 at 19:48 GMT_
_Originally opened as https://github.com/ufora/main/issues/122_

----

class C:
 def __init__(self):
  return

in Pyfora, now "C()" will return nothing!

**Comment by braxtonmckee** [comment]
Rather than actually trying to do a full transformation on __init__ that can handle this, I'm just going to disallow. We have other higher-priority items and can revisit these transformations at a later date.
