### ISSUE TITLE
Disallow 'return' statements in pyfora 'with' blocks

### ISSUE THREAD

**Issue by ronenh** [ufora/ufora#68]
Return statements are supposed to exit the enclosing function - not the with block, and we don't have a good way to implement that.

**Comment by atzannes** [comment]
I'm wondering, do we need to also check `yield` statements or do we support these?

**Comment by tdp2110** [comment]
good call. we support those inside functions, and with block bodies get
turned into functions, so we should disallow them too

On Thu, Nov 5, 2015 at 5:25 PM, Alexandros Tzannes <notifications@github.com
> wrote:

> I'm wondering, do we need to also check yield statements or do we support
> these?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/68#issuecomment-154214450>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com

**Comment by atzannes** [comment]
Fix ready, someone please review

**Comment by tdp2110** [comment]
With the typo fixes, I just pushed this to dev.
