### ISSUE TITLE
rename freeVariableMemberAccessChains

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#88]
in the objects floating aroudn in `PyObjectWalker.py`: `ClassDescription, FunctionDescription, WithBlockDescription`. Free isn't the right word here: we're also including possibly uninitialized local variables.

**Comment by ronenh** [comment]
How about calling the union of free and possibly uninitialized - "non-local"?

**Comment by tdp2110** [comment]
in python lingo, possibly uninitialized *are* local

On Wed, Nov 11, 2015 at 12:02 PM, Ronen Hilewicz <notifications@github.com>
wrote:

> How about calling the union of free and possibly uninitialized -
> "non-local"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/88#issuecomment-155847142>.
>



-- 
*Thomas Peters* | Software Engineer | *U**FORA *
115 West 27th Street 7th Floor, New York, NY 10001
Office: 646-918-6435 | Mobile: 732-610-8565
tpeters@ufora.com | www.ufora.com

**Comment by tdp2110** [comment]
no longer necessary, since @braxtonmckee's commit 7b828f6
